{{- if .Values.autoscaling.enabled -}}
---
{{- if .Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.autoscaling.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.autoscaling.annotations }}
  annotations:
{{ toYaml .Values.autoscaling.annotations | indent 4 }}
{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "application.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.resource.cpu_averageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.resource.memory_averageUtilization }}
{{- end }}