{{ if .Values.httpRoute.enabled }}
---
{{- $applicationNameTpl := include "application.name" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.ingress.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.httpRoute.gatewayName }}
    {{- if .Values.httpRoute.gatewayNamespace }}
    namespace: {{ .Values.httpRoute.gatewayNamespace }}
    {{- end }}
  hostnames:
  {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
      {{- if .Values.httpRoute.matches }}
        {{- range .Values.httpRoute.matches }}
      - {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- else }}
      - path:
          type: PathPrefix
          value: "/"
      {{- end }}
    backendRefs:
    - name: {{ template "application.name" . }}
      port: {{ .Values.httpRoute.servicePort }}
{{ end }}