{{- if and (.Values.persistence).enabled (not .Values.persistence.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{- if .Values.persistence.name }}
  name: "{{ .Values.persistence.name }}"
{{- else }}
  name: {{ template "application.name" . }}-data
{{- end }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.persistence.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.persistence.annotations }}
  annotations:
{{ include "application.tplvalues.render" ( dict "value" .Values.persistence.annotations  "context" $ ) | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.persistence.volumeMode }}  
  volumeMode: "{{ .Values.persistence.volumeMode }}"
{{- end }}
{{- if .Values.persistence.volumeName }}  
  volumeName: "{{ .Values.persistence.volumeName }}"
{{- end }}
{{- end }}