{{- if and (.Values.rbac).enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "application.name" $ }}-rolebinding-{{ .name }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- with $.Values.rbac.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "application.name" $ }}-role-{{ .name }}
subjects:
  - kind: ServiceAccount
  {{- if $.Values.serviceAccount.name }}
    name: {{ $.Values.serviceAccount.name }}
  {{- else }}
    name: {{ template "application.name" $ }}
  {{- end }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
---
{{- if and (.Values.rbac).enabled .Values.rbac.existingRoles }}
{{- range .Values.rbac.existingRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "application.name" $ }}-rolebinding-{{ .name }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- with $.Values.rbac.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "application.name" $ }}-role-{{ .name }}
subjects:
  - kind: ServiceAccount
  {{- if $.Values.serviceAccount.name }}
    name: {{ $.Values.serviceAccount.name }}
  {{- else }}
    name: {{ template "application.name" $ }}
  {{- end }}
    namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}