{{- if and (.Values.rbac).enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "application.name" $ }}-role-{{ .name }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- with $.Values.rbac.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if $.Values.rbac.annotations }}
  annotations:
{{ toYaml $.Values.rbac.annotations | indent 4 }}
{{- end }}
rules:
{{ toYaml .rules | indent 2 }}
{{- end }}
{{- end }}