---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.service.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ include "application.tplvalues.render" ( dict "value" .Values.service.annotations  "context" $ ) | indent 4 }}
{{- end }}
spec:
{{- if .Values.service.type }}
  type: {{ .Values.service.type }}
{{- end }}
  ports:
{{- if .Values.service.ports }}
{{ toYaml .Values.service.ports | indent 4 }}
{{- end }}
  selector:
{{ include "application.selectorLabels" . | indent 4 }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 4 }}
{{- end }}