{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccount" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end -}}
